### ISSUE TITLE
Server running, Vara HF seeing incoming request, nothing happens

### ISSUE THREAD

**Issue by GitMoGen** [Glitch31415/rws#1]
Hello, I was able to install on Windows 11 and when I start the sever, it asks for my call and then gives me various input options.  When I use another radio, VARA sees the incoming request but it appears that the sever is not responding or picking up.  I am using VaraC on the sending PC and radio.  I have attached a snapshot in the word document
Thanks, K9BRM

[VRWS Issues.docx](https://github.com/Glitch31415/rws/files/11730012/VRWS.Issues.docx)

**Comment by Glitch31415** [comment]
Only one person can connect to one instance of the server at a time, and interacting with the server through the command line counts as a connection. Another way of putting it is, you are trying to connect to the server through the radio when you are already connected through the terminal. Say "|disc" in the command line to disconnect and the server will interact with the connection through the modem. (a reconnect might be needed)
