### ISSUE TITLE
repo on pc 

### ISSUE THREAD

**Issue by 3dfablab** [Glitch31415/rws#2]
Hi, thanks a lot for this awesome server!
Just tested it in my pc and if the server create a folder repo, cannot put other post with the " create" fiction in |community .
Once it is wiped in the pc  everything work and a new post is visible in git page.
I'm playng with it and want to use it as vara user.
so thanks again, a text file attached.
[Nuovo documento di testo (2).txt](https://github.com/Glitch31415/rws/files/11857418/Nuovo.documento.di.testo.2.txt)

**Comment by Glitch31415** [comment]
Looking at the attached file:
First of all, don't add the "-9" as part of your callsign, because it messes with the VARA connection system and people might not be able to connect to you.
Second, I don't really understand the problem, is it not properly deleting the "repo" folder which keeps it from creating a new one for the next commit?
(Also, your log says " disconnected", which tells me something is going wrong, maybe inputting your callsign correctly will fix it, idk. Try using the latest version of the server if you aren't already)

**Comment by Glitch31415** [comment]
You may or may not need to run the java file as an administrator, it might help i'm not sure

**Comment by 3dfablab** [comment]
Thank you for your answer.

I start the server even without -9 , callsign only. Maybe I didn't explain myself well, the first time I use "create" a repo directory is created in my pc. If I try to create a new post the system gives me an error - "the repo directory already exists and is not empty". In my ignorance I simply deleted that folder and this allowed the new post to be created.

I use two instance of vara to simulate , with virtual cable, a true connections ( only audio)...so disconneted from client just to test it.

Still learning how to use, hope don't bore you too much with this requests.
All the best
alberto

**Comment by Glitch31415** [comment]
Deleting the "repo" folder is the correct thing to do in that instance. I'm wondering if you can't delete the repo because you aren't running the jar file as an administrator; with my testing, it deletes by itself before recreating the repo to make a new post.

**Comment by Glitch31415** [comment]
[vokoscreenNG-2023-06-24_09-31-07.mkv.zip](https://github.com/Glitch31415/rws/files/11857675/vokoscreenNG-2023-06-24_09-31-07.mkv.zip)
Here is a video of me testing the same function

**Comment by 3dfablab** [comment]
ok, I see.
but I'm still there......running cmd as administrator don't change.......what you mean run JAR as admin?
not enough  run cmd as admin in windows environment?
![Immagine](https://github.com/Glitch31415/rws/assets/91759342/1b3fc057-b7df-49f0-bf67-b450f6c0816d)

**Comment by Glitch31415** [comment]
i just checked my code, and it looks like it creates the repo then deletes it. so, if something keeps the repo from deleting after it creates it, and you restart the server, the rpo won't be deleted and it will error. try deleting the repo again, uploading something, then checking if the "repo" folder exists after you get the text saying your post has been uploaded. it should be deleted by then

**Comment by 3dfablab** [comment]
I'll  try. I'm just googling about jar as admin, maybe the prob is there.  tnx for your time!

**Comment by Glitch31415** [comment]
No problem, let me know if you need any more help

**Comment by 3dfablab** [comment]
Hi , see u upload a new version vrws on git.
Just test it, but no way....the repo folder still there.
I guess is somenthing related  how windows menage the permissions to write ( and it work) or delete ( and this not work).
When open properties the folder is readonly status...change it several times, gain all the power as admin possible....so I put a very brutal rmdir in my bat file....at least every time I start the server can send a post.... and by the way in community folder there are only the post  hi-readme-index-testpost but any posted by me.
Sorry for this long post.....there are a couple of idea about save the html files  (  ^ fileaddress) directly as html...and when you download a file, where it go?

**Comment by Glitch31415** [comment]
The new version of the server changed it from create-delete to delete-create-delete, so yeah there is definitely something wrong with the delete permissions on windows. I'll have to look into how to fix it.
When you download a file, the server returns the raw base64 data, which you need to copy and paste into notepad and save, then use the "certutil -decode" command on windows to convert it back into the file. You can make the command output anywhere you want.
I deleted the extra posts in the community manually, don't worry about it.

**Comment by Glitch31415** [comment]
By the way, is there a jvaa error when you try to upload things with the repo folder existing with the new version of the server? If so, it would help me figure out what's going wrong

**Comment by Glitch31415** [comment]
oh I know what the problem is, i forgot to git.close() and git.shutdown() the local repo before asking to delete it

**Comment by Glitch31415** [comment]
Ok i'm uploading a fixed version
